import assert from 'node:assert/strict';
import { demoData, normalizeAccount, validateData, validateState, change, mergePeople, undoChange, duplicateGroups, exportData, parseImport, empty } from '../src/domain/records.ts';
let checks = 0; function test(name, fn) { fn(); checks++; console.log('PASS', name); }
test('demo schema and exact same-service URL duplicate', () => { const d = validateData(demoData()); assert.equal(d.people.length, 4); assert.equal(d.accounts.length, 7); assert.equal(duplicateGroups(d).length, 1); });
test('X host, case, tracking URL normalization', () => { assert.deepEqual(normalizeAccount('X','https://www.twitter.com/FR_DEMO_AOI/?utm_x=y#foo'),normalizeAccount('X','@fr_demo_aoi')); });
test('service ID normalization', () => { assert.equal(normalizeAccount('Discord','100000000000000001').url, 'https://discord.com/users/100000000000000001'); assert.equal(normalizeAccount('VRChat','usr_00000000-0000-4000-8000-000000000001').key,'VRChat:usr_00000000-0000-4000-8000-000000000001'); });
test('URL sanitizer rejects executable/unexpected URL destinations', () => { for(const url of ['javascript:alert(1)','data:text/html,<svg>','http://x.com/a','https://x.com.evil.test/a','https://evil.test/a','https://user:pass@x.com/a','https://x.com:9999/a','https://x.com/home','https://x.com/a/status/1','https://x.com/%61','https://x.com/a\n/b']) assert.throws(() => normalizeAccount('X', url),url); });
test('names and notes remain plain text, unknown fields discarded', () => { const d = demoData();d.people[0].name='<img src=x onerror=alert(1)>'; d.people[0].notes='<script>window.xss=1</script>'; d.people[0].secret='discard';const v=validateData(d);assert.equal(v.people[0].notes,d.people[0].notes);assert.equal(v.people[0].secret,undefined); });
test('invalid import and malformed/reference data rejected', () => { assert.throws(() => parseImport('{bad'));assert.throws(()=>parseImport('{"format":"other","version":1,"data":{}}')); const d=demoData();d.accounts[0].personId='missing';assert.throws(()=>validateData(d)); const badService=demoData();badService.accounts[0].service=['X'];badService.accounts[0].url='https://vrchat.com/home/user/usr_00000000-0000-4000-8000-000000000001';assert.throws(()=>validateData(badService));const hidden=demoData();hidden.accounts[0].personId='';assert.throws(()=>validateData(hidden));const reserved=demoData();reserved.people[0].id='none';assert.throws(()=>validateData(reserved)); const e=demoData();e.people[0].name=' ';assert.throws(()=>validateData(e));const f=demoData();f.accounts[0].url='javascript:alert(1)';assert.throws(()=>parseImport(JSON.stringify({format:'friend-record',version:1,data:f}))); });
test('merge preserves aliases notes tags accounts and full undo', () => { const original={data:demoData(),undo:[]};const next=change(original,mergePeople(original.data,'demo-aoi','demo-ao'),'merge');assert.equal(next.data.people.length,3);assert.equal(next.data.accounts.length,7);assert.equal(next.data.accounts.find(a=>a.id==='demo-c6').personId,'demo-aoi');assert.ok(next.data.people[0].aliases.includes('Ao（別記録）')); assert.deepEqual(undoChange(next), original); });
test('export JSON roundtrip excludes undo', () => { const d=demoData();assert.deepEqual(parseImport(exportData(d)), d);const legacy=JSON.parse(exportData(d));legacy.format='friend-record';assert.deepEqual(parseImport(JSON.stringify(legacy)),d);legacy.format=['daredakke'];assert.throws(()=>parseImport(JSON.stringify(legacy))); });
test('undo limited to ten recoverable changes and reset undo', () => { let s={data:demoData(),undo:[]};for(let i=0;i<12;i++)s=change(s,s.data,'edit'+i);assert.equal(s.undo.length,10);const cleared=change(s,empty(),'clear');assert.deepEqual(undoChange(cleared).data,s.data); });
console.log(JSON.stringify({ checks, result: 'passed' }));
